## 1 用[numpy](https://www.runoob.com/numpy/numpy-tutorial.html)数组表示数据

In [13]:
import numpy as np

# np.array接受一个列表或者元组，构成一个numpy数组
a = [1,2,3]
b = (0.1,0.2,0.3)
c = [1]
d = [a,b]
e = [d,d]
print(np.array(a))
print(np.array(b))
print(np.array(c))
print(np.array(d)) # 这是一个2*3的二维数组，也就是数学里的矩阵
print(np.array(e)) # 这是一个2*2*3的三维数组，以此类推可以创建更高维度的数组

[1 2 3]
[0.1 0.2 0.3]
[1]
[[1.  2.  3. ]
 [0.1 0.2 0.3]]
[[[1.  2.  3. ]
  [0.1 0.2 0.3]]

 [[1.  2.  3. ]
  [0.1 0.2 0.3]]]


## 2 读取原始光谱数据

### 用下面的方法读取txt文件

In [14]:
with open('data/0.txt', 'r') as f:
    data = f.readlines()
data # data是个列表，每个元素代表光谱上的一个(波数, 强度)坐标

['4000.000000,0.012245\n',
 '3997.379913,0.012245\n',
 '3994.759825,0.012245\n',
 '3992.139738,0.012245\n',
 '3989.519651,0.012245\n',
 '3986.899563,0.012245\n',
 '3984.279476,0.012245\n',
 '3981.659389,0.012245\n',
 '3979.039301,0.012245\n',
 '3976.419214,0.012245\n',
 '3973.799127,0.012245\n',
 '3971.179039,0.012245\n',
 '3968.558952,0.012245\n',
 '3965.938865,0.012245\n',
 '3963.318777,0.012245\n',
 '3960.698690,0.012245\n',
 '3958.078603,0.012245\n',
 '3955.458515,0.012245\n',
 '3952.838428,0.012245\n',
 '3950.218341,0.010204\n',
 '3947.598253,0.012245\n',
 '3944.978166,0.012245\n',
 '3942.358079,0.012245\n',
 '3939.737991,0.012245\n',
 '3937.117904,0.012245\n',
 '3934.497817,0.012245\n',
 '3931.877729,0.012245\n',
 '3929.257642,0.012245\n',
 '3926.637555,0.012245\n',
 '3924.017467,0.012245\n',
 '3921.397380,0.012245\n',
 '3918.777293,0.012245\n',
 '3916.157205,0.012245\n',
 '3913.537118,0.010204\n',
 '3910.917031,0.010204\n',
 '3908.296943,0.012245\n',
 '3905.676856,0.012245\n',
 

In [15]:
 # 用split方法切片得到波数或者强度值
wavenum = [i.split(',')[0] for i in data]
spec = [j.split(',')[1].split() for j in data]
wavenum = np.array(wavenum, dtype=np.float16)
spec = np.array(spec, dtype=np.float16)

### 从```data```文件夹下获取除了```inchi.txt```以外的所有文件名称，存储在列表里，并且按照编号从小到大顺序排列

In [16]:
import os
filelist = 

SyntaxError: invalid syntax (517927374.py, line 2)

### 读取这些文件里的光谱强度，存储为一个数组，每行代表一条光谱，形状为(光谱数量 * 光谱维度)

In [ ]:
speclist = []
for file in filelist:
    with open

### 读取```data/inchi.txt```文件，每一行代表一个分子的InCHI（International Chemical Identifier，一种分子结构的表示方法）

In [17]:
inchis = []

## 3 使用[pandas](https://www.runoob.com/pandas/pandas-tutorial.html)对数据进行批量处理

In [ ]:
import pandas as pd

### pandas.DataFrame是一个类似表格的类
    建立一个pandas.DataFrame实例，第一列称为```spectrum```，存储读取到的光谱强度；第二列称为```inchi```，对应每个物质的InChI：

In [ ]:
df  = pd.DataFrame(
    {'spectrum':  ,
     'inchi':  }
) # 每一行对应着一个分子的光谱和InChi（结构信息）

### 使用```drop```方法并规定一定的条件，可以根据某一列的值进行筛选，丢弃掉不符合条件的行
    丢弃掉没有InChi的物质所在的行；

In [ ]:
df = df.drop()

### 使用```apply```方法可以以某一列作为输入，进行批量的操作
    使用```inchi```批量获得分子的SMILES，作为新的列```smiles```加入dataframe：

In [ ]:
'''
定义一个把InChI转换为SMILES的函数：'''
def inchi2smiles(inchi):
    return 

df['smiles'] = df['inchi'].apply(inchi2smiles)

### 继续使用```apply```，将光谱数据通过插值法批量缩小至1024维

In [ ]:
'''
定义一个插值函数：'''



df['spectrum'] = df['spectrum'].apply()

### 把这个dataframe存为```.pkl```文件，命名为```dataset.pkl```：

In [ ]:
pd.to_pickle()